# Generated by Django 4.2.8 on 2024-05-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.TextField(default='user1'),
            preserve_default=False,
        ),
    ]
