# Generated by Django 4.2.8 on 2024-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
